### ISSUE TITLE
Building Flexible Pipeline

### ISSUE THREAD

**Issue by david-gimeno** [joactr/AnnoTheia#1]
- [x] Make ```pipeline.py```work with long video clips `(José Miguel)`
- [x] Modify ```pipeline.py``` to be configurable by yaml files `(José Miguel)`
- [x] Conversion of scenes to a standard 25 fps `(José Miguel)`
- [x] Apply filter to discard faces with a bounding box smaller than 32x32 pixels `(José Miguel)`
- [x] Add new iBug face detector `(David)`
- [x] Add facial landmarks detector `(David)`
- [x] Code cleaning to allow the user to use their own models more comfortably `(David)`

**Comment by joactr** [comment]
All done!
